logging:
  level:
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} %5p [%X{traceId:-}] %-40.40logger{39} : %m%n"

---
spring:
  config:
    activate:
      on-profile: local
logging:
  level:
    com.example.boilerplate: DEBUG
    org.hibernate.SQL: DEBUG

---
spring:
  config:
    activate:
      on-profile: dev | stg | prod
logging:
  structured:
    format:
      console: ecs
    ecs:
      service:
        name: ${spring.application.name}
