-- =====================================================================
-- PostgreSQL 스키마/샘플 데이터 (단일 소스)
--   - docker compose: /docker-entrypoint-initdb.d 로 마운트되어 최초 기동 시 적재
--   - 테스트(Testcontainers): PostgreSQLContainer.withInitScript("db/schema.sql")
--
-- local/dev/prod 프로필은 ddl-auto: none 이므로 테이블을 미리 생성합니다.
-- 매핑 기준(Hibernate PostgreSQL 다이얼렉트):
--   BaseEntity.id          @GeneratedValue(IDENTITY) -> GENERATED BY DEFAULT AS IDENTITY
--   LocalDateTime          -> timestamp(6)
--   OffsetDateTime         -> timestamp(6) with time zone (timestamptz)
-- =====================================================================

CREATE TABLE IF NOT EXISTS goods (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(64)  NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(1024),
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL
);

INSERT INTO goods (id, code, name, description, created_at, updated_at) VALUES
    (1, 'GOODS-001', '문화상품권 5천원권', '문화 콘텐츠 전용 상품권', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'GOODS-002', '문화상품권 1만원권', '문화 콘텐츠 전용 상품권', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'GOODS-003', '주유 상품권 5만원권', '전국 주유소 사용 가능',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (id) DO NOTHING;

-- 명시 id 로 시드했으므로 IDENTITY 시퀀스를 시드 이후 값으로 전진시켜 충돌 방지
ALTER TABLE goods ALTER COLUMN id RESTART WITH 100;

CREATE TABLE IF NOT EXISTS coupons (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(64)  NOT NULL UNIQUE,
    name            VARCHAR(255) NOT NULL,
    discount_amount BIGINT       NOT NULL,
    status          VARCHAR(16)  NOT NULL,
    expires_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    recipient_phone VARCHAR(255),               -- 애플리케이션단 양방향 암호화 저장
    goods_id        BIGINT       NOT NULL,
    created_at      TIMESTAMP(6) NOT NULL,
    updated_at      TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_coupon_goods FOREIGN KEY (goods_id) REFERENCES goods (id)
);
