spring:
  application:
    name: boilerplate
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  config:
    import:
      - classpath:config/application-database.yaml
      - classpath:config/application-logging.yaml
      - classpath:config/application-swagger.yaml
      - optional:file:./.env[.properties]
  web:
    error:
      include-message: never
      include-binding-errors: never
      include-stacktrace: never
      include-exception: false
      whitelabel:
        enabled: false
