-- =====================================================================
-- 테스트 전용 스키마 (testsupport 픽스처용) — 운영 jar 에 실리지 않는다.
-- src/main 의 db/migration 은 비어 있으며(순수 보일러플레이트),
-- 파생 서비스가 자신의 V1__init.sql 부터 작성한다.
-- =====================================================================

CREATE TABLE samples (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    phone      VARCHAR(255),               -- 애플리케이션단 양방향 암호화 저장
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);
