-- =====================================================================
-- V1: 초기 스키마 + 예제 도메인 시드
--
-- Flyway 가 앱/테스트 부팅 시 자동 적용한다(spring.flyway 기본 설정,
-- 이력은 flyway_schema_history 테이블). 규칙:
--   * 적용된 마이그레이션은 절대 수정하지 않는다(체크섬 봉인) — 변경은 항상 새 V파일로.
--   * ddl-auto: validate 가 "엔티티 ↔ 이 DDL" 드리프트를 모든 환경의 부팅에서 잡는다.
--
-- 매핑 기준(Hibernate PostgreSQL 다이얼렉트):
--   BaseEntity.id          @GeneratedValue(IDENTITY) -> GENERATED BY DEFAULT AS IDENTITY
--   Instant                -> timestamp(6) with time zone  (환경 TZ 무관 동일 의미)
--   OffsetDateTime         -> timestamp(6) with time zone
-- =====================================================================

CREATE TABLE goods (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(64)  NOT NULL UNIQUE,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(1024),
    created_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

INSERT INTO goods (id, code, name, description, created_at, updated_at) VALUES
    (1, 'GOODS-001', '문화상품권 5천원권', '문화 콘텐츠 전용 상품권', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, 'GOODS-002', '문화상품권 1만원권', '문화 콘텐츠 전용 상품권', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, 'GOODS-003', '주유 상품권 5만원권', '전국 주유소 사용 가능',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- 명시 id 로 시드했으므로 IDENTITY 시퀀스를 시드 이후 값으로 전진시켜 충돌 방지
ALTER TABLE goods ALTER COLUMN id RESTART WITH 100;

CREATE TABLE coupons (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(64)  NOT NULL UNIQUE,
    name            VARCHAR(255) NOT NULL,
    discount_amount BIGINT       NOT NULL,
    status          VARCHAR(16)  NOT NULL,
    expires_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    recipient_phone VARCHAR(255),               -- 애플리케이션단 양방향 암호화 저장
    goods_id        BIGINT       NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_coupon_goods FOREIGN KEY (goods_id) REFERENCES goods (id)
);
